### ISSUE TITLE
Dummy data within card

### ISSUE THREAD

**Issue by asha-hegde** [ajency/devicebook-web#15]
The list of devices that needs to be connected with the DApp is the same in all the cards. 
![D10](https://user-images.githubusercontent.com/51397558/59421898-0d373c00-8ded-11e9-8232-378311dd8328.png)

**Comment by AJ-Shank** [comment]
Please note there is still an incomplete functionality that the card should show the name of the softdevice in the expanded view. and should show max of 3/4 devices in the closed view.

Can we make an issue around that?
