### ISSUE TITLE
Pagination - highlight

### ISSUE THREAD

**Issue by asha-hegde** [ajency/devicebook-web#17]
Click on any page navigation buttons -> observe that the clicked button does get highlighted.

Add rel=prev/next in the pagination list for next and previous pages.
`<link rel="prev" href="http://www.example.com/article?story=abc&page=1" />`
`<link rel="next" href="http://www.example.com/article?story=abc&page=3" />`

**Comment by jeromie** [comment]
@AJ-Shank this will have to be handled in handlebars. Based on the current page, the active class will have to be assigned for the respective link.

**Comment by AJ-Shank** [comment]
@jeromie Adding of the `active` class does not change any CSS

**Comment by jeromie** [comment]
@AJ-Shank active class to be added for li .page-item
Below is screenshot with active class added for first page
![image](https://user-images.githubusercontent.com/5372828/59503078-18f23380-8ebd-11e9-929f-84b0bea79e72.png)

**Comment by 27amaldev09** [comment]
@jeromie ya its working

**Comment by AJ-Shank** [comment]
Adding a point to the description of the issue. Please add this to the html

**Comment by AJ-Shank** [comment]
Add rel=prev/next in the pagination list for next and previous pages.
`<link rel="prev" href="http://www.example.com/article?story=abc&page=1" />`
`<link rel="next" href="http://www.example.com/article?story=abc&page=3" />`

**Comment by asha-hegde** [comment]
Resolved
